import type { Command } from "commander";
import { writeDesignContext } from "../lib/design-context.js";
import { defaultConfig, writeFileIfMissing, writeJson } from "../lib/project.js";
import { syncAshlarProject } from "../lib/styles.js";
import { writeThemeFiles } from "../lib/theme.js";

const agentsTemplate = `# Ashlar - Agent Instructions

This project uses Ashlar components. When generating UI code:

- Use installed Ashlar capsules from ashlar-lock.json.
- Preserve semantic HTML and accessible names.
- For L0 components, use semantic platform markup (e.g. \`<button class="ashlar-button" data-variant="primary">\`), not custom elements.
- Do not remove focus-visible styles.
- Use Ashlar CSS variables for styling (e.g. \`var(--ashlar-color-action-primary-bg)\`); do not hard-code brand colors.
- Run \`ashlar audit\` before considering generated UI complete; resolve all errors.

This file is regenerated by \`ashlar init\` and \`ashlar design sync\`. Customizations should be made downstream of the regenerated content (e.g. in a project-specific section appended below).
`;

export function registerInitCommand(program: Command) {
  program
    .command("init")
    .description("Initialize Ashlar in this project")
    .option("--force", "Overwrite existing Ashlar config files")
    .option("--registry <path>", "Registry path or URL", "./registry")
    .option(
      "--components-dir <path>",
      "Installed component source directory",
      "src/ashlar/components",
    )
    .option(
      "--entrypoint <path>",
      "Generated Ashlar stylesheet entrypoint",
      "src/ashlar/ashlar.css",
    )
    .action(
      (options: {
        componentsDir: string;
        entrypoint: string;
        force?: boolean;
        registry: string;
      }) => {
        const force = Boolean(options.force);
        const config = defaultConfig({
          registry: options.registry,
          componentsDir: options.componentsDir,
          indexesDir: "src/ashlar/indexes",
          styles: {
            entrypoint: options.entrypoint,
            theme: "src/ashlar/themes/theme.css",
          },
        });

        writeJson("ashlar.config.json", config);

        const lockfile = {
          $schema: "https://ashlar.dev/schemas/lock.schema.json",
          version: "1",
          registry: config.registry,
          components: {},
        } as const;

        writeJson("ashlar-lock.json", lockfile);
        writeThemeFiles(config, force);
        syncAshlarProject(process.cwd(), config, lockfile);

        writeFileIfMissing("AGENTS.md", agentsTemplate, force);
        writeDesignContext("DESIGN.md", force);
        console.log("Initialized Ashlar");
      },
    );
}
