import {
  lstatSync,
  mkdirSync,
  readFileSync,
  readlinkSync,
  symlinkSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { dirname, relative } from "node:path";
import type { AshlarLockfile, ResolvedAshlarConfig } from "./project.js";

export type AgentInstructionSyncResult = {
  path: string;
  status: "linked" | "copied" | "skipped";
  reason?: string;
};

export const agentInstructionTargets = [
  "CLAUDE.md",
  ".cursor/rules/ashlar.mdc",
  ".windsurfrules",
  ".continuerules",
  ".github/copilot-instructions.md",
] as const;

function installedCapsuleLines(lockfile: AshlarLockfile): string {
  const entries = Object.entries(lockfile.components).sort(([a], [b]) => a.localeCompare(b));

  if (entries.length === 0) {
    return "- No Ashlar capsules are installed yet.";
  }

  return entries
    .map(
      ([name, component]) => `- ${name}@${component.version} (${component.stability ?? "unknown"})`,
    )
    .join("\n");
}

export function buildAgentsContext(config: ResolvedAshlarConfig, lockfile: AshlarLockfile): string {
  return `# Ashlar - Agent Instructions

This project uses Ashlar capsules: source-owned public-service UI with evidence, policy mappings, and validator rules.

## Installed Capsules

${installedCapsuleLines(lockfile)}

## Project Paths

- Registry: \`${config.registry}\`
- Components: \`${config.componentsDir}\`
- Stylesheet entrypoint: \`${config.styles.entrypoint}\`
- Component index: \`${config.indexesDir}/components.json\`

## Discovery Workflow

- For a new public-service UI task, start with \`ashlar suggest "<task>"\` to get a deterministic capsule plan.
- Use \`ashlar search --policy <text>\`, \`ashlar search --feature <text>\`, or \`ashlar search --token <text>\` when the task is tied to a standard, platform capability, or token.
- Before installing or using a capsule, inspect it with \`ashlar view <component>\` and \`ashlar evidence <component>\`.
- In MCP-capable agents, prefer read-only \`suggest_for_task\`, \`search_components\`, \`get_component\`, \`get_evidence\`, \`list_tokens\`, \`get_token\`, and \`validate_usage\`.
- Treat \`suggest_for_task\` and \`ashlar suggest\` as planning aids only. They never install components, write files, or prove accessibility conformance.

## Rules For AI Coding Agents

- Use only installed Ashlar capsules unless the user explicitly asks to add a new capsule; if adding is requested, run the discovery workflow first.
- Do not invent props, variants, classes, or behaviors that are absent from the installed CEM files.
- Preserve semantic HTML, accessible names, label associations, focus-visible styles, and forced-colors behavior.
- For markup primitive capsules (internal layer L0), use semantic platform markup such as \`<button class="ashlar-button" data-variant="primary">\`, not custom elements.
- Use Ashlar CSS variables for styling; do not hard-code agency colors into capsule source.
- After editing Ashlar markup, run \`ashlar audit --policy all\` or the repo-local equivalent.
- Before claiming installed capsule integrity, run \`ashlar verify\`.

This file is generated by Ashlar. Keep project-specific notes in a separate section or file if you need local conventions.
`;
}

export function writeAgentsContext(
  path: string,
  config: ResolvedAshlarConfig,
  lockfile: AshlarLockfile,
): AgentInstructionSyncResult[] {
  const parent = dirname(path);
  if (parent !== ".") {
    mkdirSync(parent, { recursive: true });
  }

  const contents = buildAgentsContext(config, lockfile);
  writeFileSync(path, contents);

  return syncAgentInstructionFiles(path, contents);
}

export function syncAgentInstructionFiles(
  canonicalPath: string,
  contents: string,
): AgentInstructionSyncResult[] {
  return agentInstructionTargets.map((targetPath) =>
    syncAgentInstructionFile(canonicalPath, targetPath, contents),
  );
}

function syncAgentInstructionFile(
  canonicalPath: string,
  targetPath: string,
  contents: string,
): AgentInstructionSyncResult {
  const parent = dirname(targetPath);
  if (parent !== ".") {
    mkdirSync(parent, { recursive: true });
  }

  const target = linkTarget(canonicalPath, targetPath);
  const existing = readExisting(targetPath);

  if (existing?.kind === "symlink") {
    if (existing.link === target) {
      return { path: targetPath, status: "linked" };
    }

    unlinkSync(targetPath);
  } else if (existing?.kind === "file") {
    if (isManagedCopy(existing.contents)) {
      writeFileSync(targetPath, copiedInstructions(contents));
      return { path: targetPath, status: "copied" };
    }

    return {
      path: targetPath,
      status: "skipped",
      reason: "existing file is not managed by Ashlar",
    };
  } else if (existing?.kind === "other") {
    return {
      path: targetPath,
      status: "skipped",
      reason: "existing path is not a file or symlink",
    };
  }

  try {
    symlinkSync(target, targetPath);
    return { path: targetPath, status: "linked" };
  } catch {
    writeFileSync(targetPath, copiedInstructions(contents));
    return { path: targetPath, status: "copied" };
  }
}

function readExisting(
  path: string,
):
  | { kind: "file"; contents: string }
  | { kind: "symlink"; link: string }
  | { kind: "other" }
  | undefined {
  try {
    const stat = lstatSync(path);
    if (stat.isSymbolicLink()) {
      return { kind: "symlink", link: readlinkSync(path) };
    }
    if (stat.isFile()) {
      return { kind: "file", contents: readFileSync(path, "utf8") };
    }

    return { kind: "other" };
  } catch {
    return undefined;
  }
}

function linkTarget(canonicalPath: string, targetPath: string): string {
  const targetParent = dirname(targetPath);
  const target = relative(targetParent, canonicalPath);
  return target || canonicalPath;
}

function copiedInstructions(contents: string): string {
  return `<!-- Ashlar-managed copy of AGENTS.md. Re-run ashlar init, add, or update to refresh. -->\n\n${contents}`;
}

function isManagedCopy(contents: string): boolean {
  return contents.startsWith("<!-- Ashlar-managed copy of AGENTS.md.");
}
