import type { AshlarLockfile, ResolvedAshlarConfig } from "./project.js";
import { writeFileIfMissing } from "./project.js";
import { getComponent } from "./registry.js";
import { findThemeToken, loadStockThemes, type ThemeDefinition } from "./theme.js";

type DesignContextOptions = {
  cwd: string;
};

type InstalledDesignCapsule = {
  name: string;
  version: string;
  stability: string;
  tier?: string;
  layer?: string;
  evidence?: string;
  platformFeatures?: string[];
  policyMappings?: string[];
};

export function buildDesignContext(
  config: ResolvedAshlarConfig,
  lockfile: AshlarLockfile,
  options: DesignContextOptions,
): string {
  const theme = defaultTheme();
  const tokens = designTokens(theme);
  const capsules = installedDesignCapsules(config, lockfile, options.cwd);

  return `---
name: Ashlar ${theme.title}
description: Government-first, evidence-backed public-service UI system.
theme:
  name: ${theme.name}
  title: ${JSON.stringify(theme.title)}
colors:
  page: ${JSON.stringify(tokens.page)}
  surface: ${JSON.stringify(tokens.surface)}
  action-primary: ${JSON.stringify(tokens.actionPrimary)}
  focus-ring: ${JSON.stringify(tokens.focus)}
typography:
  body:
    fontFamily: ${JSON.stringify(tokens.fontSans)}
spacing:
  control-min-block-size: ${JSON.stringify(tokens.buttonMinBlockSize)}
rounded:
  control: ${JSON.stringify(tokens.controlRadius)}
---

## Source

This file is an agent-facing export generated by Ashlar. It is not the canonical design source. Canonical values live in Ashlar tokens, component manifests, evidence packets, and policy packs.

## Project Paths

- Registry: \`${config.registry}\`
- Components: \`${config.componentsDir}\`
- Stylesheet entrypoint: \`${config.styles.entrypoint}\`
- Theme CSS: \`${config.styles.theme}\`
- Typed tokens: \`${config.styles.tokenTypes}\`

## Installed Capsules

${installedCapsuleLines(capsules)}

## Component Discovery

- Start new public-service UI tasks with \`ashlar suggest "<task>"\` or MCP \`suggest_for_task\`.
- Use \`ashlar search\` or MCP \`search_components\` with policy, feature, token, layer, stability, or evidence filters when choosing capsules.
- Inspect candidate capsules with \`ashlar view <component>\`, \`ashlar evidence <component>\`, MCP \`get_component\`, and MCP \`get_evidence\` before using them.
- Suggestions are deterministic metadata matches. They do not install components, modify files, or prove accessibility conformance.

## Token Rules

- Use generated Ashlar CSS variables instead of hard-coded agency colors.
- Primary action background: \`${tokens.actionPrimaryVariable}\` (${tokens.actionPrimary}).
- Focus ring: \`${tokens.focusVariable}\` (${tokens.focus}).
- Control radius: \`${tokens.controlRadiusVariable}\` (${tokens.controlRadius}).
- Button radius: \`${tokens.buttonRadiusVariable}\` (${tokens.buttonRadius}).
- If a token is missing, add it to the agency theme source before using it.

## Interface Rules

- Use a restrained, trustworthy civic interface.
- Prioritize clarity, plain language, visible focus, and resilient layouts over novelty.
- Preserve focus indicators, label associations, error summaries, and forced-colors behavior.
- Keep forms dense enough for repeat use but readable at 200% zoom.
- Do not invent props, variants, classes, or behaviors outside installed Ashlar capsule manifests.
- Do not use decorative gradients or oversized marketing layouts for operational government flows.

## Validation

- After editing Ashlar markup, run \`ashlar audit --policy all\` or the repo-local equivalent.
- Before claiming installed capsule integrity, run \`ashlar verify\`.
- For AI-assisted changes, prefer the local MCP tools \`suggest_for_task\`, \`search_components\`, \`get_component\`, \`get_evidence\`, \`list_tokens\`, \`get_token\`, and \`validate_usage\`.
`;
}

export function writeDesignContext(
  path: string,
  config: ResolvedAshlarConfig,
  lockfile: AshlarLockfile,
  options: DesignContextOptions & { force?: boolean },
): boolean {
  return writeFileIfMissing(
    path,
    buildDesignContext(config, lockfile, options),
    options.force ?? true,
  );
}

function defaultTheme(): ThemeDefinition {
  const themes = loadStockThemes();
  const theme = themes.find((item) => item.name === "default") ?? themes[0];
  if (!theme) {
    throw new Error("No Ashlar themes are available.");
  }

  return theme;
}

function designTokens(theme: ThemeDefinition) {
  const page = findThemeToken(theme, "color.page");
  const surface = findThemeToken(theme, "color.surface");
  const actionPrimary = findThemeToken(theme, "color.action.primary.bg");
  const focus = findThemeToken(theme, "color.focus");
  const fontSans = findThemeToken(theme, "font.sans");
  const controlRadius = findThemeToken(theme, "radius.control");
  const buttonRadius = findThemeToken(theme, "component.button.radius");
  const buttonMinBlockSize = findThemeToken(theme, "component.button.minBlockSize");

  return {
    page: page?.value ?? "#ffffff",
    surface: surface?.value ?? "#ffffff",
    actionPrimary: actionPrimary?.value ?? "#005ea8",
    actionPrimaryVariable: actionPrimary?.cssVariable ?? "--ashlar-color-action-primary-bg",
    focus: focus?.value ?? "#2491ff",
    focusVariable: focus?.cssVariable ?? "--ashlar-color-focus",
    fontSans: fontSans?.value ?? "system-ui, sans-serif",
    controlRadius: controlRadius?.value ?? "0.25rem",
    controlRadiusVariable: controlRadius?.cssVariable ?? "--ashlar-radius-control",
    buttonRadius:
      buttonRadius?.resolvedValue ?? buttonRadius?.value ?? "var(--ashlar-radius-control)",
    buttonRadiusVariable: buttonRadius?.cssVariable ?? "--ashlar-button-radius",
    buttonMinBlockSize: buttonMinBlockSize?.value ?? "2.75rem",
  };
}

function installedDesignCapsules(
  config: ResolvedAshlarConfig,
  lockfile: AshlarLockfile,
  cwd: string,
): InstalledDesignCapsule[] {
  return Object.entries(lockfile.components)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, component]) => {
      try {
        const detail = getComponent(cwd, name, config.registry);
        return {
          name,
          version: component.version,
          stability: component.stability ?? detail.stability,
          tier: detail.tier,
          layer: detail.layer,
          evidence: detail.evidence.accessibilityStatus,
          platformFeatures: detail.platformFeatures.map((feature) => feature.feature),
          policyMappings: detail.policyMappings.map((mapping) => mapping.source),
        };
      } catch {
        return {
          name,
          version: component.version,
          stability: component.stability ?? "unknown",
        };
      }
    });
}

function installedCapsuleLines(capsules: InstalledDesignCapsule[]): string {
  if (capsules.length === 0) {
    return "- No Ashlar capsules are installed yet.";
  }

  return capsules
    .map((capsule) => {
      const metadata = [
        capsule.tier,
        capsule.layer,
        capsule.stability,
        capsule.evidence ? `evidence: ${capsule.evidence}` : undefined,
      ]
        .filter(Boolean)
        .join(", ");
      const features = capsule.platformFeatures?.length
        ? `\n  - Platform features: ${capsule.platformFeatures.join(", ")}`
        : "";
      const mappings = capsule.policyMappings?.length
        ? `\n  - Policy mappings: ${capsule.policyMappings.join(", ")}`
        : "";

      return `- ${capsule.name}@${capsule.version}${metadata ? ` (${metadata})` : ""}${features}${mappings}`;
    })
    .join("\n");
}
