import { writeFileIfMissing } from "./project.js";

export const designContextTemplate = `---
name: Ashlar Default
description: Government-first, evidence-backed public-service UI system.
colors:
  action-primary: "#005EA8"
  focus-ring: "#2491FF"
typography:
  body:
    fontFamily: Public Sans
    fontSize: 1rem
spacing:
  md: 16px
rounded:
  control: 6px
---

## Source

This file is an agent-facing export generated by Ashlar. It is not the canonical design source. Canonical values live in Ashlar tokens, component manifests, evidence packets, and policy packs.

## Overview

Use a restrained, trustworthy civic interface. Prioritize clarity, plain language, visible focus, and resilient layouts over novelty.

## Do's and Don'ts

- Do use Ashlar tokens and installed components.
- Do preserve focus indicators and forced-colors behavior.
- Do keep forms dense enough for repeat use but readable at 200% zoom.
- Do not invent brand colors outside the agency theme.
- Do not remove focus-visible styles.
- Do not use decorative gradients or oversized marketing layouts for operational government flows.
`;

export function writeDesignContext(path = "DESIGN.md", force = true): boolean {
  return writeFileIfMissing(path, designContextTemplate, force);
}
