import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type { AshlarLockfile, ResolvedAshlarConfig } from "./project.js";
import { getComponent } from "./registry.js";
import { writeThemeCssFromProject } from "./theme.js";

function readIfExists(path: string): string {
  return existsSync(path) ? readFileSync(path, "utf8") : "";
}

function componentCssPath(config: ResolvedAshlarConfig, name: string): string {
  return join(config.componentsDir, name, `${name}.css`);
}

export function syncAshlarProject(
  cwd: string,
  config: ResolvedAshlarConfig,
  lockfile: AshlarLockfile,
): void {
  mkdirSync(dirname(config.styles.entrypoint), { recursive: true });
  mkdirSync(config.indexesDir, { recursive: true });
  writeThemeCssFromProject(config);

  const components = Object.entries(lockfile.components).sort(([a], [b]) => a.localeCompare(b));
  const componentCss = components
    .map(([name]) => {
      const path = componentCssPath(config, name);
      const css = readIfExists(path);

      return css ? `/* Ashlar component: ${name} */\n${css.trim()}\n` : "";
    })
    .filter(Boolean)
    .join("\n");

  const entrypoint =
    `/* Generated by Ashlar. Do not edit directly; edit tokens or component source instead. */\n@layer ashlar.tokens, ashlar.base, ashlar.components;\n\n${readIfExists(
      config.styles.theme,
    ).trim()}\n\n@layer ashlar.base {\n  :where(.ashlar-sr-only) {\n    block-size: 1px;\n    clip: rect(0 0 0 0);\n    clip-path: inset(50%);\n    inline-size: 1px;\n    overflow: hidden;\n    position: absolute;\n    white-space: nowrap;\n  }\n}\n\n${componentCss}`.trimEnd();

  writeFileSync(config.styles.entrypoint, `${entrypoint}\n`);

  const componentIndex = components.map(([name, installed]) => {
    try {
      const detail = getComponent(cwd, name, config.registry);

      return {
        name,
        version: installed.version,
        tier: detail.tier,
        layer: detail.layer,
        stability: detail.stability,
        description: detail.description,
        accessibilityStatus: detail.evidence.accessibilityStatus,
        sourceFiles: Object.keys(installed.files).sort(),
      };
    } catch {
      return {
        name,
        version: installed.version,
        stability: installed.stability ?? "unknown",
        sourceFiles: Object.keys(installed.files).sort(),
      };
    }
  });

  writeFileSync(
    join(config.indexesDir, "components.json"),
    `${JSON.stringify({ generatedBy: "ashlar-cli@0.0.0", components: componentIndex }, null, 2)}\n`,
  );

  writeFileSync(
    join(config.indexesDir, "evidence.json"),
    `${JSON.stringify(
      {
        generatedBy: "ashlar-cli@0.0.0",
        components: componentIndex.map((component) => ({
          name: component.name,
          version: component.version,
          accessibilityStatus:
            "accessibilityStatus" in component ? component.accessibilityStatus : "unknown",
        })),
      },
      null,
      2,
    )}\n`,
  );
}
